In [1]:
#dataframe정렬:sort_values()
#list정렬:list.sort(), sorted(list)
#tuple정렬:sorted(tuple,키)

#정렬:선택,버블,삽입,...(O(n^2))
#퀵,병합,힙(O(nlogn))
#계수(O(m+n))#데이터 정렬: 

In [ ]:
#                        DF                Series
# 행 개수 세기        len(df)             len(s)
#                     df.shape[0]          s.size
#                    len(df.index)        len(s.index)
# 열 개수 세기        df.shape[1]             x
#                   len(df.columns)
# NULL 아닌 행 개수   df.count()            s.count()
# 그룹단위 행 개수     df.groupby().size()    s.groupby().size()     
# 그룹단위 NULL 아닌 행 개수 df.groupby().count() 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import re

In [5]:
df = pd.DataFrame ({'s':[1,3,2],
              'name':['choi','kim','lee'],
              'age':[30,20,40]})
df

TypeError: sort_values() missing 1 required positional argument: 'by'

In [10]:
df.sort_values(by='s',ascending=False, kind ='quicksort',inplace=True)

In [7]:
df.sort(axis=1)

AttributeError: 'DataFrame' object has no attribute 'sort'

In [13]:
tp = [(1,'park',30),
     (2,'lee',20),
     (3,'choi',40)]
tp

[(1, 'park', 30), (2, 'lee', 20), (3, 'choi', 40)]

In [15]:
sorted(tp, key=lambda la:la[2]) #la로 tp가 전달되어 la의 튜플

[(2, 'lee', 20), (1, 'park', 30), (3, 'choi', 40)]

In [16]:
mylist=[0,9,7,2,4]
sorted(mylist)

[0, 2, 4, 7, 9]

In [85]:
mylist.sort()
mylist

[0, 2, 4, 7, 9]

In [20]:
df = pd.DataFrame({'grp': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'],  
                           'val': [1, 2, np.nan, 4, np.nan, np.nan, 7, 8, 9]}) 
s = pd.Series([1, 2, np.nan, 4, np.nan, np.nan, 7, 8, 9])
df

grp  val
0   A  1.0
1   A  2.0
2   A  NaN
3   B  4.0
4   B  NaN
5   B  NaN
6   C  7.0
7   C  8.0
8   C  9.0

In [24]:
len(df)
df.shape[0]
len(df.index)

9

In [26]:
len(s)
s.size
len(s.index)

9

In [28]:
df.shape[1]
len(df.columns)

(9, 2)

In [31]:
df.count()
df['val'].count()
s.count()

df.groupby('grp').size() #NaN 포함한 각 그룹의 행 개수
df.groupby('grp').count()#NaN을 제외한 각 그룹의 행 개수

6

In [ ]:
s.groupby(df.grp).size() #NaN 포함한 각 그룹의 행 개수
s.groupby(df.grp).count()#NaN을 제외한 각 그룹의 행 개수

In [32]:
df = pd.DataFrame({'id': ['A_001', 'A_002', 'A_003', 'B_001', 'C_001', 'C_002'],  
                          'val': np.arange(6)})
df

id  val
0  A_001    0
1  A_002    1
2  A_003    2
3  B_001    3
4  C_001    4
5  C_002    5

In [36]:
df.id
df.id.split('_') # --> split은 문자열함수에서 사용 가능하다
df.id.str.split('_')

AttributeError: 'Series' object has no attribute 'split'

In [40]:
df.id.str.split('_') # str써서 문자열로 형변환 시켜주고
df.id.str.split('_')[0] # [0]번 인덴스 행 데이터
df.id.str.split('_').str[0] # 인덱스의 첫 글자만 추출
df

id  val
0  A_001    0
1  A_002    1
2  A_003    2
3  B_001    3
4  C_001    4
5  C_002    5

In [41]:
df.id.str.split('_').str[0].tolist() # --> 시리즈에서 리스트로 형변환 가능 

['A', 'A', 'A', 'B', 'C', 'C']

In [45]:
for i in range(df.shape[0]):
#     print(df.loc[i,'val'].split('_')[0])
    df.loc[i,'gg'] = df.loc[i,'val'].split('_')[0]

AttributeError: 'numpy.int32' object has no attribute 'split'

In [49]:
df = pd.DataFrame({'c1':[1,3], 'c2':[2,4]})
df
df.assign(c3=df['c1']*df['c2']) #--> assign은 할당할 뿐 저장되지 않는다
df

c1  c2
0   1   2
1   3   4

In [50]:
# 데이터프레임의 컬럼 삭제
# del df[열이름]  df.drop([열이름],1) 
# .drop()은 데이터 자체가 삭제되는 것은 아니다
# del df['c3'] --> del은 갱신이 되어 두 번 실행되면 에러가 뜬다

SyntaxError: invalid syntax (<ipython-input-50-63b1f0d87be1>, line 2)

In [51]:
df

c1  c2
0   1   2
1   3   4

In [ ]:
# 텍스트를 단어로 분리 --> 단어 단위 원핫인코딩

# how are you
# what is your name

# how는 1번으로 인덱싱 --> 1000000
# are는 2번으로 --> 0100000

# 전처리에서 is/are는 be로 you/your는 you로 처리되면 7개 단어  --> 5개 단어
#따라서 원핫인코딩시 7개에서 5개로 단어가 줄어듬

In [70]:
file_opened = open('python_wikipedia.txt')
file_opened
# file_opened.readlines()
for line in file_opened.readlines():
    print(line)
    
# 전처리(소문자, stopword, 콤마, 대괄호, 특수문자, ... , 숫자)
def word_preprocess(word):
    word = word.lower()  # 단어를 소문자로 바꿔줌
    stop_words = ['a', 'an', 'the', 'in', 'with', 'to', 'for', 'from', 'of', 'at', 'on', 'until', 'by', 'and', 'but', 'is', 'are', 'was', 'were', 'it', 'that', 'this', 'my', 'his', 'her', 'our', 'as', 'not'] # make your own list
    symbols = [',', '.', ':', '-', '+', '/', '*', '&', '%', '[', ']', '(', ')'] # make your own list
    
    for stop_word in stop_words:
        if word != stop_word: #불용어가 아닐경우
            word=word
        else:
            word=''
    for symbol in symbols:
        word.replace(symbol,'') # word 내에서의 특수문자 제거는 replace로 공백처리해준다
    return word       
            

            

Python programming language, from wikipedia

Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aims to help programmers write clear, logical code for small and large-scale projects.[26]

Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including procedural, object-oriented, and functional programming. Python is often described as a "batteries included" language due to its comprehensive standard library.[27]

Python was conceived in the late 1980s as a successor to the ABC language. Python 2.0, released 2000, introduced features like list comprehensions and a garbage collection system capable of collecting reference cycles. Python 3.0, released 2008, was a major revision of the language that is not completel

In [72]:
file_opened = open('python_wikipedia.txt')
for line in file_opened.readlines():
    # 앞뒤 공백 제거 --> strip()
    line = line.strip()
    # print(line)
    for word in line.split():
        word = word_preprocess(word)
        print(word)

python
programming
language,

wikipedia
python


interpreted,
high-level,
general-purpose
programming
language.
created

guido
van
rossum

first
released

1991,
python's
design
philosophy
emphasizes
code
readability

its
notable
use

significant
whitespace.
its
language
constructs

object-oriented
approach
aims

help
programmers
write
clear,
logical
code

small

large-scale
projects.[26]
python

dynamically
typed

garbage-collected.

supports
multiple
programming
paradigms,
including
procedural,
object-oriented,

functional
programming.
python

often
described


"batteries
included"
language
due

its
comprehensive
standard
library.[27]
python

conceived


late
1980s


successor


abc
language.
python
2.0,
released
2000,
introduced
features
like
list
comprehensions


garbage
collection
system
capable

collecting
reference
cycles.
python
3.0,
released
2008,


major
revision


language



completely
backward-compatible,

much
python
2
code
does

run
unmodified

python
3.
due

concern
abou

In [73]:
# 각 단어별로 몇 번씩 쓰였는지에 대한 딕셔너리를 만들고 싶다면?

token_inx = {} # --> 빈 딕셔너리 생성
file_opened = open('python_wikipedia.txt')
for line in file_opened.readlines():
    # 앞뒤 공백 제거 --> strip()
    line = line.strip()
    # print(line)
    for word in line.split():
        word = word_preprocess(word)
        if word not in token_inx: # 토큰inx 안에 word에 해당하는 문자열이 없다면,(token_inx에서 key로 확인함)
            if word != '': # 공백아닌 순수 단어라면
                token_inx[word]=1 # 1은 value의 초기값으로 들어간다
                #token_inx[word]=len(token_inx)+1
        else:
            token_inx[word]=token_inx[word]+1
print(token_inx)

{'python': 14, 'programming': 3, 'language,': 1, 'wikipedia': 1, 'interpreted,': 1, 'high-level,': 1, 'general-purpose': 1, 'language.': 2, 'created': 1, 'guido': 2, 'van': 2, 'rossum': 2, 'first': 1, 'released': 3, '1991,': 1, "python's": 1, 'design': 1, 'philosophy': 1, 'emphasizes': 1, 'code': 4, 'readability': 1, 'its': 3, 'notable': 1, 'use': 1, 'significant': 1, 'whitespace.': 1, 'language': 4, 'constructs': 1, 'object-oriented': 1, 'approach': 1, 'aims': 1, 'help': 1, 'programmers': 2, 'write': 1, 'clear,': 1, 'logical': 1, 'small': 1, 'large-scale': 1, 'projects.[26]': 1, 'dynamically': 1, 'typed': 1, 'garbage-collected.': 1, 'supports': 1, 'multiple': 1, 'paradigms,': 1, 'including': 1, 'procedural,': 1, 'object-oriented,': 1, 'functional': 1, 'programming.': 1, 'often': 1, 'described': 1, '"batteries': 1, 'included"': 1, 'due': 2, 'comprehensive': 1, 'standard': 1, 'library.[27]': 1, 'conceived': 1, 'late': 1, '1980s': 1, 'successor': 1, 'abc': 1, '2.0,': 1, '2000,': 1, 'intr

In [77]:
# Nympy의 표본 추출 함수

np.random.normal(5,size=3) # 정규분포로부터 3개의 랜덤 값을 생성해줌(평균 5를 만족하는)

array([5.89396485, 4.31592703, 7.69912011])

In [78]:
np.random.seed(708)
np.random.normal(size=10)

array([-0.44701866,  0.42271748,  0.35076078, -0.15413394, -1.5020158 ,
        1.30307833,  1.00748836,  0.06666045, -1.47430939, -0.39288867])

In [ ]:
#  binomial : 이항분포로부터 무작위 표본추출 
# 이산형/ 연속형 확률 분포
# 이산형(이항, 포아송)
# 연속형 (정규, t분포, 균등, f, 카이제곱 등)

# 성공1 실패0, 성공확률p, 베르누이 시행을 n번 수행, 성공하는 횟수를 x라 하면
# 확률 변수x는 모수 n과 p인 이항 분포를 따른다 라고 표현한다
# f(x) = nCx p^x (1-p)^n-x, x=0,1,...,n 


# n개 중 r개 추출 nCr (순서 상관x)
# ex) 주사위 (5,3) 이나 (3,5) 같다

# nCx 에서 x는 0부터 n까지 가지는 횟수


In [80]:
np.random.binomial(n=1,p=0.5,size=20)

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0])

In [81]:
sum(np.random.binomial(n=1,p=0.5,size=20)==1)/20

0.45

In [84]:
# 정규분포를 따르는 난수를 발생
# np.ramdom.normal(mu, sigma, size)
np.random.normal(0,3,100)


array([ 1.5370588 ,  2.39292138,  3.3512172 , -4.2842833 , -4.55406869,
        4.24234311,  1.30057018,  0.895461  , -0.43727831, -0.14655071,
       -0.56577133, -2.33287759,  2.6771022 , -3.47648854, -0.09214297,
        3.32509782, -0.63574142,  0.18675766, -1.87080797, -1.21456478,
       -0.43458814, -1.25167771, -2.20515387, -2.44936339,  3.98588931,
        3.54156261, -2.49184564, -2.00578431,  3.46666957,  1.75534793,
       -1.85587612,  4.11226051, -1.82249905,  5.08921616, -2.6942552 ,
       -4.24375425,  7.36352146,  0.28220585, -0.27808825,  4.23707537,
        1.80913906, -4.06653688, -0.92869466,  3.34404997,  2.04035521,
        0.10898017,  0.98188226, -1.48505134,  1.14984669, -3.656114  ,
        2.22571485, -1.75208816, -0.99799926,  0.7927612 ,  2.83020632,
       -3.17093664, -0.63203011, -5.48890198,  2.8050894 , -3.95254499,
       -0.53223889,  2.17131378,  0.20490759, -4.58187782, -1.97621464,
        2.21116709, -1.9702217 ,  0.02622525, -1.37888258, -0.95