In [ ]:
sequential api 이용한 layer 구성

In [51]:
from keras.models import Model
from keras.models import Sequential
from keras.layers import *

models=Sequential()
model.add(Dense(3,input_dim=4,activation='softmax'))

In [ ]:
input api 이용한 layer 구성

In [4]:
from keras.layers import Input,Dense
from keras.models import Model

inputs=Input(shape=(10,))
hid1=Dense(32,activation='relu')(inputs)
hid2=Dense(32,activation='relu')(hid1)
output=Dense(1,activation='sigmoid')(hid2)
model=Model(inputs=inputs, outputs=output)

model.compile(optimizer='rmsprop',loss='categorical_crossentropy'

W0823 09:21:20.244178 13236 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0823 09:21:20.271179 13236 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0823 09:21:20.274180 13236 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [5]:
import numpy as np

In [8]:
timesteps=10 # 시점, 문장을 구성하는 10개의 단어가 input으로 들어가기 위해 준비되어 있다.
# 주식 예측 모델에서 timestep=7이면, 7일간의 주식변동 패턴으로 오늘 주가를 예상하겠다
input_dim=4 #단어가4개인 벡터(코퍼스내의 단어의 갯수)
hidden_size=8 # 은닉상태의 크기(셀)
inputs=np.random.random((timesteps,input_dim))
inputs

array([[0.07746269, 0.09863809, 0.75294896, 0.97111548],
       [0.50788023, 0.57179806, 0.13454343, 0.51323235],
       [0.14765247, 0.87468056, 0.40706533, 0.61652796],
       [0.0237201 , 0.68450242, 0.99959291, 0.18958987],
       [0.7487826 , 0.66572016, 0.62740426, 0.49272446],
       [0.8874179 , 0.83108996, 0.68344134, 0.18740409],
       [0.90846003, 0.99836163, 0.36914458, 0.47864696],
       [0.90442159, 0.60167611, 0.84401427, 0.32493716],
       [0.19517487, 0.10885897, 0.90927465, 0.52592748],
       [0.07871028, 0.06524201, 0.07805278, 0.85962331]])

### 초기 은닉 상태를 0으로 초기화

In [10]:
hidden_state_t=np.zeros((hidden_size,))

#가중치 (은닉상태의크기*입력차원)
wx=np.random.random((hidden_size,input_dim)) #(8, 4)
#은닉상태 가중치 (은닉상태의크기*은닉상태의크기)
wh=np.random.random((hidden_size,hidden_size)) #(8, 8)
#b바이어스(은닉상태의크기)
b=np.random.random((hidden_size,)) #8

print(np.shape(wx))

(8, 4)


### 메모리 셀 동작

In [13]:
total_hidden_state=[]

for input_t in inputs:
#     print(input_t)
    output_t=np.tanh(np.dot(wx,input_t)+np.dot(wh,hidden_state_t)+b) # wx*input+wh*ht-1+b    
#     print(output_t)
    total_hidden_state.append(list(output_t))
#     print(total_hidden_state)
    hidden_state_t=output_t #다음 입력셀로 현재의 상태를 넘겨줌

[[0.89790680283983, 0.9685316824479632, 0.9278098474397086, 0.7781697218474337, 0.8914505191933109, 0.872155087414267, 0.8929521814802948, 0.8003733370046235]]
[[0.89790680283983, 0.9685316824479632, 0.9278098474397086, 0.7781697218474337, 0.8914505191933109, 0.872155087414267, 0.8929521814802948, 0.8003733370046235], [0.8413480266119114, 0.9156483432111513, 0.8791600397846323, 0.5907565717864424, 0.8479739039781957, 0.8011440608857231, 0.7542954637014524, 0.8472257660125944]]
[[0.89790680283983, 0.9685316824479632, 0.9278098474397086, 0.7781697218474337, 0.8914505191933109, 0.872155087414267, 0.8929521814802948, 0.8003733370046235], [0.8413480266119114, 0.9156483432111513, 0.8791600397846323, 0.5907565717864424, 0.8479739039781957, 0.8011440608857231, 0.7542954637014524, 0.8472257660125944], [0.9252447302375002, 0.9634795309176902, 0.9499118805632921, 0.6618073128125166, 0.9245690794810768, 0.7938657646612571, 0.8210405465056458, 0.9050450362973117]]
[[0.89790680283983, 0.968531682447

In [15]:
text="""멀티캠퍼스에 있는 교육생들이 공부하고 있다\n
교육생들은 딥러닝을 하고있다\n
결석한 교육생도 있고 지각한 교육생도 있다\n
"""

xdata                  y
멀티캠퍼스에          있는
멀티캠퍼스에 있는   교육생들이
....
멀티캠퍼스에,3  --> 있는 교육생들이 공부하고

In [14]:
from keras.preprocessing.text import Tokenizer 

In [38]:
t=Tokenizer()
t.fit_on_texts([text]) #단어에 인덱스 붙여줌
t.texts_to_sequences([text]) #인덱스만 단어 순서에 따라 출력
print(t.texts_to_sequences([text]))
print(t.word_index) #단어당 인덱스를 함께 출력

[[3, 4, 5, 6, 1, 7, 8, 9, 10, 2, 11, 12, 2, 1]]
{'있다': 1, '교육생도': 2, '멀티캠퍼스에': 3, '있는': 4, '교육생들이': 5, '공부하고': 6, '교육생들은': 7, '딥러닝을': 8, '하고있다': 9, '결석한': 10, '있고': 11, '지각한': 12}


In [39]:
vocab_size=len(t.word_index)+1 #단어 집합의 크기:13
# 입력:멀티캠퍼스 , 단어수2
# 출력:있는 교육생들이

for line in text.split("\n"):
    print(line)
    print(t.texts_to_sequences([line])[0])

    
sequences=list()
for line in text.split("\n"):
#     print(t.texts_to_sequences([line])[0])
    encoded=t.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence=encoded[:i+1]
#         print(sequence)
        sequences.append(sequence)
print(len(sequences))
print(sequences)
        
print(max(len(s) for s in sequences))
max_len=max(len(s) for s in sequences)

멀티캠퍼스에 있는 교육생들이 공부하고 있다
[3, 4, 5, 6, 1]

[]
교육생들은 딥러닝을 하고있다
[7, 8, 9]

[]
결석한 교육생도 있고 지각한 교육생도 있다
[10, 2, 11, 12, 2, 1]

[]

[]
11
[[3, 4], [3, 4, 5], [3, 4, 5, 6], [3, 4, 5, 6, 1], [7, 8], [7, 8, 9], [10, 2], [10, 2, 11], [10, 2, 11, 12], [10, 2, 11, 12, 2], [10, 2, 11, 12, 2, 1]]
6


In [40]:
from keras.preprocessing.sequence import pad_sequences
sequences=pad_sequences(sequences,maxlen=max_len)
sequences

array([[ 0,  0,  0,  0,  3,  4],
       [ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  3,  4,  5,  6],
       [ 0,  3,  4,  5,  6,  1],
       [ 0,  0,  0,  0,  7,  8],
       [ 0,  0,  0,  7,  8,  9],
       [ 0,  0,  0,  0, 10,  2],
       [ 0,  0,  0, 10,  2, 11],
       [ 0,  0, 10,  2, 11, 12],
       [ 0, 10,  2, 11, 12,  2],
       [10,  2, 11, 12,  2,  1]])

In [47]:
x=sequences[:,:-1]
y=sequences[:,-1]
x
y

array([ 4,  5,  6,  1,  8,  9,  2, 11, 12,  2,  1])

### one-hot encoding

In [36]:
from keras.utils import to_categorical

In [48]:
y=to_categorical(y,num_classes=vocab_size)
y

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [49]:
from keras.layers import *
x
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',
             optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=300,verbose=2) 

W0823 13:46:59.882737 13236 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0823 13:47:00.051738 13236 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/300
 - 1s - loss: 2.5773 - acc: 0.0000e+00
Epoch 2/300
 - 0s - loss: 2.5697 - acc: 0.0000e+00
Epoch 3/300
 - 0s - loss: 2.5611 - acc: 0.0000e+00
Epoch 4/300
 - 0s - loss: 2.5521 - acc: 0.0000e+00
Epoch 5/300
 - 0s - loss: 2.5428 - acc: 0.0000e+00
Epoch 6/300
 - 0s - loss: 2.5333 - acc: 0.0000e+00
Epoch 7/300
 - 0s - loss: 2.5236 - acc: 0.0000e+00
Epoch 8/300
 - 0s - loss: 2.5137 - acc: 0.0000e+00
Epoch 9/300
 - 0s - loss: 2.5034 - acc: 0.0000e+00
Epoch 10/300
 - 0s - loss: 2.4929 - acc: 0.0000e+00
Epoch 11/300
 - 0s - loss: 2.4820 - acc: 0.1818
Epoch 12/300
 - 0s - loss: 2.4707 - acc: 0.2727
Epoch 13/300
 - 0s - loss: 2.4589 - acc: 0.2727
Epoch 14/300
 - 0s - loss: 2.4466 - acc: 0.3636
Epoch 15/300
 - 0s - loss: 2.4338 - acc: 0.3636
Epoch 16/300
 - 0s - loss: 2.4204 - acc: 0.3636
Epoch 17/300
 - 0s - loss: 2.4065 - acc: 0.3636
Epoch 18/300
 - 0s - loss: 2.3920 - acc: 0.4545
Epoch 19/300
 - 0s - loss: 2.3769 - acc: 0.4545
Epoch 20/300
 - 0s - loss: 2.3612 - acc: 0.4545
Epoch 21/

Epoch 170/300
 - 0s - loss: 0.1947 - acc: 1.0000
Epoch 171/300
 - 0s - loss: 0.1906 - acc: 1.0000
Epoch 172/300
 - 0s - loss: 0.1867 - acc: 1.0000
Epoch 173/300
 - 0s - loss: 0.1828 - acc: 1.0000
Epoch 174/300
 - 0s - loss: 0.1791 - acc: 1.0000
Epoch 175/300
 - 0s - loss: 0.1754 - acc: 1.0000
Epoch 176/300
 - 0s - loss: 0.1719 - acc: 1.0000
Epoch 177/300
 - 0s - loss: 0.1684 - acc: 1.0000
Epoch 178/300
 - 0s - loss: 0.1650 - acc: 1.0000
Epoch 179/300
 - 0s - loss: 0.1618 - acc: 1.0000
Epoch 180/300
 - 0s - loss: 0.1586 - acc: 1.0000
Epoch 181/300
 - 0s - loss: 0.1554 - acc: 1.0000
Epoch 182/300
 - 0s - loss: 0.1524 - acc: 1.0000
Epoch 183/300
 - 0s - loss: 0.1495 - acc: 1.0000
Epoch 184/300
 - 0s - loss: 0.1466 - acc: 1.0000
Epoch 185/300
 - 0s - loss: 0.1438 - acc: 1.0000
Epoch 186/300
 - 0s - loss: 0.1410 - acc: 1.0000
Epoch 187/300
 - 0s - loss: 0.1384 - acc: 1.0000
Epoch 188/300
 - 0s - loss: 0.1358 - acc: 1.0000
Epoch 189/300
 - 0s - loss: 0.1332 - acc: 1.0000
Epoch 190/300
 - 0s 

In [50]:
def word_gen(model, t, curr_word, num):
          #모델,토큰나이저,입력단어,개수
        ini_word=curr_word
        sent=''
        for _ in range(num):
            #print(t.word_index)
            encoded=t.texts_to_sequences([curr_word])[0] #[3]
            #print(encoded)
            encoded=pad_sequences([encoded],maxlen=5,padding='pre') # [[0 0 0 0 3]]
            #print(encoded)           
            res=model.predict_classes(encoded)
            #print(res) #4
            for word, index in t.word_index.items():
                if res==index: #동일한 단어를 찾았다면
                    break
            curr_word=curr_word+' '+word 
            sent=sent+' '+word            
        sent=ini_word+sent
        return sent      
print(word_gen(model, t, '멀캠', 10))    
#멀티캠퍼스에 라는 단어 뒤에 3개의 단어 예측

멀캠 교육생도 딥러닝을 하고있다 교육생들이 있다 있다 있다 있다 있다 있다


In [52]:
import pandas as pd

In [54]:
df=pd.read_csv("/Users/user/Downloads/ArticlesApril2018.csv")
df.columns
len(df.columns)

15

In [55]:
df['headline']

0       Former N.F.L. Cheerleaders’ Settlement Offer: ...
1       E.P.A. to Unveil a New Rule. Its Effect: Less ...
2                                 The New Noma, Explained
3                                                 Unknown
4                                                 Unknown
5                                                 Unknown
6                                                 Unknown
7                                                 Unknown
8       How a Bag of Texas Dirt  Became a Times Tradition
9                  Is School a Place for Self-Expression?
10                                 Commuter Reprogramming
11                                                Unknown
12                                                Unknown
13      Ford Changed Leaders, Looking for a Lift. It’s...
14      Romney Failed to Win at Utah Convention, But F...
15                                         Chain Reaction
16      He Forced the Vatican to Investigate Sex Abuse...
17            

In [58]:
headline=[]
headline.extend(list(df.headline.values))
headline

headline=[n for n in headline if n != 'Unknown']
len(headline)
# headline
#     print(n)

1214

In [69]:
from string import punctuation
def mypreprocessing(s):# 점 제거,소문자로 변환
    # 전처리된 문장을 return하겠다.
#     s.lower()
#     print(s)
#     print(punctuation)
#     return s#전처리된 문장
#     print(''.join(ch for ch in s if ch not in punctuation).lower())
    return ''.join(ch for ch in s if ch not in punctuation).lower()

text=[mypreprocessing(x) for x in headline] #변환되기 전 문장
print(len(text))

1214


In [74]:
# vocabulary 작성
t=Tokenizer()
t.fit_on_texts(text)
t.word_index
vocab_size=len(t.word_index)+1 # 단어 집합의 크기:3620개(중복되지 않는 단어 갯수)
vocab_size

3620

In [75]:
sequences=[]
for line in text: #1214개의 라인
    encoded=t.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence=encoded[:i+1]
        sequences.append(sequence)
    print(sequences[:20])

[[95, 263], [95, 263, 1100], [95, 263, 1100, 1101], [95, 263, 1100, 1101, 572], [95, 263, 1100, 1101, 572, 50], [95, 263, 1100, 1101, 572, 50, 7], [95, 263, 1100, 1101, 572, 50, 7, 2], [95, 263, 1100, 1101, 572, 50, 7, 2, 365], [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10], [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10, 1102]]
[[95, 263], [95, 263, 1100], [95, 263, 1100, 1101], [95, 263, 1100, 1101, 572], [95, 263, 1100, 1101, 572, 50], [95, 263, 1100, 1101, 572, 50, 7], [95, 263, 1100, 1101, 572, 50, 7, 2], [95, 263, 1100, 1101, 572, 50, 7, 2, 365], [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10], [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10, 1102], [96, 3], [96, 3, 1103], [96, 3, 1103, 2], [96, 3, 1103, 2, 14], [96, 3, 1103, 2, 14, 573], [96, 3, 1103, 2, 14, 573, 85], [96, 3, 1103, 2, 14, 573, 85, 1104], [96, 3, 1103, 2, 14, 573, 85, 1104, 366], [96, 3, 1103, 2, 14, 573, 85, 1104, 366, 367], [96, 3, 1103, 2, 14, 573, 85, 1104, 366, 367, 5]]
[[95, 263], [95, 263, 1100], [95, 263, 1100, 1

In [77]:
max_len_headline=max(len(s) for s in sequences )

In [78]:
from keras.preprocessing.sequence import pad_sequences
sequences=pad_sequences(sequences,maxlen=max_len_headline)
sequences

array([[   0,    0,    0, ...,    0,   95,  263],
       [   0,    0,    0, ...,   95,  263, 1100],
       [   0,    0,    0, ...,  263, 1100, 1101],
       ...,
       [   0,    0,    0, ...,    9, 3619,  110],
       [   0,    0,    0, ..., 3619,  110,    2],
       [   0,    0,    0, ...,  110,    2, 1014]])

In [79]:
x=sequences[:,:-1]
y=sequences[:,-1]
x
y

array([ 263, 1100, 1101, ...,  110,    2, 1014])

In [80]:
y=to_categorical(y,num_classes=vocab_size)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [82]:
from keras.layers import *
x
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_len_headline-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',
             optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=300,verbose=2) 

Epoch 1/300
 - 2s - loss: 7.7206 - acc: 0.0270
Epoch 2/300
 - 2s - loss: 7.1950 - acc: 0.0289
Epoch 3/300
 - 2s - loss: 7.0254 - acc: 0.0375
Epoch 4/300
 - 2s - loss: 7.0640 - acc: 0.0393
Epoch 5/300
 - 2s - loss: 6.7919 - acc: 0.0483
Epoch 6/300
 - 2s - loss: 6.6586 - acc: 0.0511
Epoch 7/300
 - 2s - loss: 6.5383 - acc: 0.0551
Epoch 8/300
 - 2s - loss: 6.4223 - acc: 0.0565
Epoch 9/300
 - 2s - loss: 6.3080 - acc: 0.0647
Epoch 10/300
 - 2s - loss: 6.1972 - acc: 0.0659
Epoch 11/300
 - 2s - loss: 6.0901 - acc: 0.0679
Epoch 12/300
 - 2s - loss: 5.9828 - acc: 0.0744
Epoch 13/300
 - 2s - loss: 5.8777 - acc: 0.0756
Epoch 14/300
 - 2s - loss: 5.7709 - acc: 0.0789
Epoch 15/300
 - 2s - loss: 5.6689 - acc: 0.0820
Epoch 16/300
 - 2s - loss: 5.5661 - acc: 0.0864
Epoch 17/300
 - 2s - loss: 5.4663 - acc: 0.0898
Epoch 18/300
 - 2s - loss: 5.3677 - acc: 0.0937
Epoch 19/300
 - 2s - loss: 5.2715 - acc: 0.0982
Epoch 20/300
 - 2s - loss: 5.1750 - acc: 0.1067
Epoch 21/300
 - 2s - loss: 5.0839 - acc: 0.1095
E

Epoch 171/300
 - 2s - loss: 0.7282 - acc: 0.8499
Epoch 172/300
 - 2s - loss: 0.7254 - acc: 0.8509
Epoch 173/300
 - 2s - loss: 0.7168 - acc: 0.8515
Epoch 174/300
 - 2s - loss: 0.7079 - acc: 0.8552
Epoch 175/300
 - 2s - loss: 0.7130 - acc: 0.8515
Epoch 176/300
 - 2s - loss: 0.7137 - acc: 0.8512
Epoch 177/300
 - 2s - loss: 0.7000 - acc: 0.8543
Epoch 178/300
 - 2s - loss: 0.6896 - acc: 0.8570
Epoch 179/300
 - 2s - loss: 0.6895 - acc: 0.8540
Epoch 180/300
 - 2s - loss: 0.7083 - acc: 0.8506
Epoch 181/300
 - 2s - loss: 0.7089 - acc: 0.8488
Epoch 182/300
 - 2s - loss: 0.6806 - acc: 0.8567
Epoch 183/300
 - 2s - loss: 0.6699 - acc: 0.8611
Epoch 184/300
 - 2s - loss: 0.6546 - acc: 0.8626
Epoch 185/300
 - 2s - loss: 0.6554 - acc: 0.8612
Epoch 186/300
 - 2s - loss: 0.6449 - acc: 0.8653
Epoch 187/300
 - 2s - loss: 0.6532 - acc: 0.8629
Epoch 188/300
 - 2s - loss: 0.6552 - acc: 0.8618
Epoch 189/300
 - 2s - loss: 0.6586 - acc: 0.8598
Epoch 190/300
 - 3s - loss: 0.6601 - acc: 0.8603
Epoch 191/300
 - 2s 

In [84]:
def word_gen(model, t, curr_word, num):
          #모델,토큰나이저,입력단어,개수
        ini_word=curr_word
        sent=''
        for _ in range(num):
            #print(t.word_index)
            encoded=t.texts_to_sequences([curr_word])[0] #[3]
            #print(encoded)
            encoded=pad_sequences([encoded],maxlen=23,padding='pre') # [[0 0 0 0 3]]
            #print(encoded)           
            res=model.predict_classes(encoded)
            #print(res) #4
            for word, index in t.word_index.items():
                if res==index: #동일한 단어를 찾았다면
                    break
            curr_word=curr_word+' '+word 
            sent=sent+' '+word            
        sent=ini_word+sent
        return sent      
print(word_gen(model, t, 'saturday', 10))    
#멀티캠퍼스에 라는 단어 뒤에 3개의 단어 예측

saturday night out 1978 the gaza base life tolerance and a


In [ ]:
import os
model.save(os.path.join("/Users/user/Desktop/,"NYT_headline.h5"))