In [7]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

In [ ]:
## step function 

In [ ]:
x>0 면, 1을 반환
x<0이면, 0을 반환하는 활성함수

In [38]:
def step_func(x):
    return np.array(x>0,dtype=int)
#     if x>0:
#         return 1
#     else:
#         return 0
    
step_func(10)

array(1)

In [9]:
## sigmoid function

In [10]:
def sigmoid(x): # x에 결과가 전달된다 --> 시그모이드 함수를 통해 0~1사이 값으로 변환한다.
    return 1/(1+np.exp(-x))

In [17]:
x=np.arange(-5.0,5.0,0.1)
y1=sigmoid(x)
y1
y2=step_func(x)
y2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
## ReLu function

In [19]:
def relu(x):
    return np.maximum(0,x)

In [21]:
relu(9)

9

In [27]:
A= np.array([1,2,3,4])
np.ndim(A)
A.shape
A.shape[0]
B=np.array([[1,2],[3,4],[5,6]])
np.ndim(B)
B.shape

(3, 2)

In [24]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [28]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[5,6],[7,8],[9,10]])
np.dot(A,B)

array([[ 46,  52],
       [109, 124]])

In [36]:
# 입력 x1,x2 출력 y1,y2,y3 가중치 1,3,5/2,4,6
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X,W)
Y

array([ 5, 11, 17])

In [44]:
X=np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B2 = np.array([0.1,0.2,0.3])
A1 = np.dot(X,W1)+B1
A1
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [48]:
W2=np.array([[0.1,0.3],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])
print(Z1.shape)
A2=np.dot(Z1,W2)+B2
Z2=sigmoid(A2)
Z2

(3,)


array([0.62624937, 0.76071122])

In [49]:
W3=np.array([[0.1,0.3],[0.2,0.4]])
B3=np.array([[0.1,0.2]])
A3=np.dot(Z2,W3)+B3
A3

array([[0.31476718, 0.6921593 ]])

In [51]:
a=np.array([0.3,2.9,4.0])
exp_a=np.array(a)
exp_a

array([0.3, 2.9, 4. ])

In [ ]:
sum_exp_a=np.sum(exp_a)
y=exp_a/sum_exp_a
y

In [52]:
# from dataset.mnist import load_mnist

ModuleNotFoundError: No module named 'dataset'

In [54]:
import tensorflow as tf

In [58]:
sess=tf.Session()
hi=tf.constant("hi")
print(sess.run(hi))
print(str(sess.run(hi),encoding='utf-8'))

b'hi'
hi


In [ ]:
def dist_word(t1,t2):
    
    return num

text=input('기준 문자열을 입력하세요: ')
text2=input('대상 문자열을 입력하세요: ')
print(" 두 단어의 거리는 %d입니다", num)