# 텐서(Tensor)
* 정의: 0차원부터 n차원까지 다양한 차원을 가지는 배열

* '훈련 데이터를 가지고 학습을 시켜서 적정한 값을 찾는다' 라는 머신러닝 학습 모델의 특성상 
   모델을 그래프로 정의하고, 세션을 만들어서 그래프를 실행하고, 세션이 실행될 때 
   그래프에 동적으로 값을 넣어가면서 (피딩) 실행한 다는 기본 개념


## 상수형 자료(Constant)

In [19]:
import tensorflow as tf

In [23]:
#상수형 자료를 저장할 때 사용, float32가 default
# a,b,c,d는 연산은 안하지만, 저장하고 있는 노드이다. (저장도 연산의 일부다)
a=tf.constant([5],dtype=tf.float32) 
a=tf.constant([5]) # 5만 출력된다. 
b=tf.constant([10],dtype=tf.float32)
c=tf.constant([2],dtype=tf.float32)
d=a*b+c

sess = tf.Session()
sess.run(a)

array([5.], dtype=float32)

## 세션을 생성하여 그래프를 실행
## 세션: 그래프를 실행시켜주는 runner

## 플레이스 홀더 
* training을 하기 위한 자료를 임시 저장하는 저장소
* training해야 graph가 실행되고, graph가 실행되어야 model이 만들어진다
* 학습을 위한 데이터를 담는 데이터 타입

## feeding(피딩) 
* 학습용 데이터를 딕셔너리 형태로 전달하는 행위
* x에 학습용 데이터를 전달하는 방법이다

In [25]:
x=tf.placeholder(dtype=tf.float32)
y=x*2
sess.run(y,feed_dict={x:[1,2,3,4]})


array([2., 4., 6., 8.], dtype=float32)

## 변수(Variable)
* 모델링 과정(트레이닝 과정)에서 변화하는 기울기나 절편과 같은 것
* 텐서플로우의 변수형은 그래프 실행 전, 초기화를 해주어야 변수에 지정이 된다

In [ ]:
hf=wx+b
#hf=0.5x+2

In [29]:
# input=tf.Variable([1,2,3])
inputData=[1,2,3]
x=tf.placeholder(dtype=tf.float32)
w=tf.Variable([2],dtype=tf.float32) # 변수 선언을 하기 위해 초기화하는 작업이 필요하다
yhat=w*x

sess=tf.Session()
sess.run(tf.global_variables_initializer())
# 위와 같은 의미의 코드이다
# init = tf.global_variables_initializer()
# sess.run(init)
sess.run(yhat,feed_dict={x:inputData})

array([2., 4., 6.], dtype=float32)

In [36]:
# tf.matmul( , )
# row=[1,2,3]
# col=[2,2,2]
# arr_row = np.array(row)
# arr_col = np.array(col)
# x=tf.placeholder(dtype=tf.float32)
# test = tf.matmul(row.T,col)

# sess=tf.Session()
# sess.run(tf.global_variables_initializer())
# sess.run(test,feed_dict={x:row})

x=tf.constant([[1,2,3]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
print(sess.run(y))
print(sess.run(y)[0][0])

array([[12]])

In [38]:
x=tf.Variable([[1,2,3]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
sess.run(tf.global_variables_initializer())
sess.run(y)

array([[12]])

In [39]:
x=tf.Variable([[1,2,3],[1,2,3],[2,3,4]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
sess.run(tf.global_variables_initializer())
sess.run(y)

array([[12],
       [12],
       [18]])

In [ ]:
x=tf.Variable([[1,2,3],[1,2,3],[2,3,4]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
sess.run(tf.global_variables_initializer())
sess.run(y)

## None : 아직 결정되지 않은 상태


In [46]:
indata=[[1,2,3],[1,2,3],[2,3,4]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3]) 
# 학습마다 데이터양이 달라질 수 있다
# shpae속성에 행/열 중 결정되지 않은 부분은 None으로 주어 
# 데이터를 읽을 때마다 대체가 되도록 할 수 있다
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
sess.run(tf.global_variables_initializer())
sess.run(y)

TypeError: Input 'b' of 'MatMul' Op has type int32 that does not match type float32 of argument 'a'.

In [45]:
data=[[1,1,1],[2,2,2]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3])
w=tf.Variable([[2],[2],[2]],dtype=tf.float32)
b=tf.Variable([4],dtype=tf.float32)
y=tf.matmul(x,w)+b
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y,feed_dict={x:data})

array([[10.],
       [16.]], dtype=float32)

In [ ]:
apple=100
appleNum=2
orange=150
orangeNum=3
tax=1.1

# price출력(100*2+150*3)*1.1
# dapple
# dappleNum
# dorange
# dorangeNum
# dtax

In [ ]:
class MulLayer:
    def _init_(self): # self는 현재 만들어지는 붕어빵
        self.x=None # x 붕어빵 길이
        self.y=None # y 붕어빵 너비
        sess=tf.Session()
        sess.run(tf.global_variables_initializer())


    def forward(self,x,y):
        self.x=tf.placeholder(dtype=tf.float32) # 객체에 저장하려고 하는 부분
        self.y=tf.placeholder(dtype=tf.float32)
        out=tf.matmul(self.x1,w1)+tf.matmul(self.x2,w2)+b
#         sess.run(out,feed_dict=self.x)
        return out      
    
    def backward(self,dout):
        dx=tf.matmul(dout,self.y)
        dy=tf.matmul(dout,self.x)
        return dx,dy

In [ ]:
mal=MulLayer()
mtl=MulLayer()

apple=100
appleNum=2
orange=150
orangeNum=3
tax=1.1

apple_price=mal.forward(apple,appleNum)
price =mtl.forward(apple_price,tax)
dprice=1
dapple_price, dtax=mtl.backward(dprice)
print(dprice,dapple_price,dtax)

In [76]:
import numpy as np

def googoo(dan):
    
    x=tf.placeholder(dtype=tf.float32) #,shape=[None,1]
    w=tf.Variable(np.arange(1,10),dtype=tf.float32)
#     y=tf.matmul(x,w)
    y=x*w
    sess=tf.Session()
    sess.run(tf.global_variables_initializer())
    
    print(sess.run(y,feed_dict={x:dan}))
    
# googoo(9)
googoo(8)
# (np.arange(1,10)).shape

# # input=tf.Variable([1,2,3])
# inputData=[1,2,3]
# x=tf.placeholder(dtype=tf.float32)
# w=tf.Variable([2],dtype=tf.float32) # 변수 선언을 하기 위해 초기화하는 작업이 필요하다
# yhat=w*x

# sess=tf.Session()
# sess.run(tf.global_variables_initializer())
# # 위와 같은 의미의 코드이다
# # init = tf.global_variables_initializer()
# # sess.run(init)
# sess.run(yhat,feed_dict={x:inputData})

ValueError: Shape must be at least rank 2 but is rank 1 for 'MatMul_20' (op: 'BatchMatMulV2') with input shapes: ?, [9].