In [1]:
import tensorflow as tf

In [2]:
tf.range(5)

<tf.Tensor 'range:0' shape=(5,) dtype=int32>

### linspace

In [3]:
tf.linspace(0.0,5,11) # 시작값은 무조건 float타입이어야한다

<tf.Tensor 'LinSpace:0' shape=(11,) dtype=float32>

### 배열 선언하기 (zeros, ones, fill) 

In [4]:
tf.zeros((2,3)) #상수 텐서: 상수로 쓰여진 텐서

<tf.Tensor 'zeros:0' shape=(2, 3) dtype=float32>

In [5]:
tf.ones((2,3))

<tf.Tensor 'ones:0' shape=(2, 3) dtype=float32>

In [7]:
tf.fill([3,3],5) # 3*3 크기의 행렬을 5로 채운다

<tf.Tensor 'Fill_1:0' shape=(3, 3) dtype=int32>

In [ ]:
tf.zeros_like(x) #x가 2*3크기라면, 똑같이 2*3크기가 만들어진다

In [11]:
tf.random.set_random_seed(777) 
tf.set_random_seed(777) #동일한 난수 생성 --> 매번 램덤 생성시, 비교불가
tf.random.shuffle([1,2,3,4])

<tf.Tensor 'RandomShuffle_1:0' shape=(4,) dtype=int32>

### reshape, transpose

In [ ]:
tf.reshape(x,(3,2)) #x가 1차원벡터였는데, 3*2 벡터로 바꾸고 싶다면
tf.transpose(x) # 전치행렬

### slice / split

In [22]:
r0=tf.reshape(tf.range(12),(3,4))
r0
sess = tf.Session()
print(sess.run(r0))
r1= tf.slice(r0,[0,1],[2,3]) #[0,1]의 위치에서 [2,3]을 추출하겠다
print(sess.run(r1))
s1,s2 = tf.split(r0,num_or_size_splits=2,axis=1)
print(sess.run(s1))
print(sess.run(s2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2 3]
 [5 6 7]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


### 요소간의 사칙연산

In [27]:
a=tf.range(6,dtype=tf.float32)
b=2*tf.ones(6,dtype=tf.float32)
sess.run(a)
sess.run(b)
sess.run(tf.add(a,b))
sess.run(tf.subtract(a,b))
sess.run(tf.multiply(a,b))
sess.run(tf.divide(a,b))

array([0. , 0.5, 1. , 1.5, 2. , 2.5], dtype=float32)

### 많이 사용하는 함수

In [ ]:
tf.abs() # 절댓값 구하기
tf.square() # 제곱 구하기
tf.sqru() #제곱근 구하기
tf.cumsum() #누적합 구하기
tf.minimum()
tf.maximum()

### reduce_연산이름( )
* reduce_() 는 계산하면 결과값이 차원이 축소된다 

In [ ]:
tf.reduce_mean() # axis가 설정 된 축을 기준으로 평균을 구함 
tf.reduce_sum()
tf.reduce_min()
tf.reduce_max()

### tf.linalg(x) : x의 역행렬

In [31]:
x=tf.constant([[2,0],[0,1]],dtype=tf.float32)
y=tf.constant([[1,1],[1,1]],dtype=tf.float32)
z=tf.matmul(x,y)
print(sess.run(z))

xinv=tf.linalg.inv(x) # 역행렬
print(sess.run(xinv))

[[2. 2.]
 [1. 1.]]
[[0.5 0. ]
 [0.  1. ]]


### tf.sigmoid( ): 로지스틱 함수